spring:
  application:
    name: strategy-launches-analyzer
  http:
    converters:
      preferred-json-mapper: jackson2
    codecs:
      preferred-json-mapper: jackson2
  lifecycle:
    timeout-per-shutdown-phase: 70s

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState
      show-details: never

server:
  shutdown: graceful

springdoc:
  api-docs:
    enabled: false
  paths-to-match: /api/v1/**
